# SERVER NET WORK
HOST = '0.0.0.0'
PORT = 10021
SERVER_LISTEN = 1

# CLIENT WORK
SERVER_HOST = '192.168.0.13' # lab_215

# GAME STATUS
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500

# CONTROL
LEFT = "'LEFT' key pressed"
RIGHT = "'RIGHT' key pressed"
UP = "'UP' key pressed"
DOWN = "'DOWN' key pressed"